### ISSUE TITLE
Error occurred When I run " python osvos_demo.py" in windows

### ISSUE THREAD

**Issue by 5kejun** [scaelles/OSVOS-TensorFlow#10]
Error occurred When I run " python osvos_demo.py" in windows 7 X64  command line. As followed: 
=== RESTART: E:\My Documents\python\OSVOS-TensorFlow-master\osvos_demo.py ===
Traceback (most recent call last):
  File "E:\My Documents\python\OSVOS-TensorFlow-master\osvos_demo.py", line 20, in <module>
    import osvos
  File "E:\My Documents\python\OSVOS-TensorFlow-master\osvos.py", line 152
    print 'input + output channels need to be the same'
                                                      ^
SyntaxError: Missing parentheses in call to 'print'                                                                                                         PS.  I had unzip parent model(55 MB) and pre-trained models(2.2GB) under models/. Moreover, unzipped DAVIS-2017-test-dev-480p.zip in the root directory

**Comment by gdshen** [comment]
The code was written by python2, Tensorflow on windows only support py3. You can use 2to3 to convert this repo into py3-compatible, or you can wrap the "print" statement into print() function.

**Comment by kmaninis** [comment]
Hi, we never tried the code for Windows, however the specific error, as @gdshen pointed, looks like a Python version error.
