### ISSUE TITLE
What are the GPU memory requirements to run this program?

### ISSUE THREAD

**Issue by kaisark** [scaelles/OSVOS-TensorFlow#12]
What are the GPU memory requirements to run this program?

Can this code run on a Nvidia TX1 with 4GB of memory?

Will the code (if configured) run using multiple GPU if I push to AWS P2 instance?

**Comment by kmaninis** [comment]
Hello,

We checked on TensorFlow 1.1, and training takes approximately 6.4G of GPU memory.
There may be optimizations for the newest TF version, which we did not try.

I hope it helps.
