### ISSUE TITLE
Performance Metrics

### ISSUE THREAD

**Issue by imraviagrawal** [scaelles/OSVOS-TensorFlow#14]
Can you please point out where and how you are calculating the performance metric in the code. 

I don't seem to find the script for the validation results. 

If the script is not available in the code can you please share the appropriate script to recreate your results.

**Comment by kmaninis** [comment]
Hi, for the DAVIS metrics there are two repos, written in MATLAB and Python, respectively. You can access them here: http://davischallenge.org/davis2016/code.html

In order not to update everything twice, we kept those two contributions separate. I hope this helps.

**Comment by imraviagrawal** [comment]
Thanks, I will check the repo.
