### ISSUE TITLE
Machine configuration

### ISSUE THREAD

**Issue by feitiandemiaomi** [scaelles/OSVOS-TensorFlow#18]
@scaelles Hi, Thank your great repo, I read your paper  saying the model can process a frame in 102ms, What is your machine? and  have you try the lighter network to improve efficiency ？

**Comment by kmaninis** [comment]
Hi, we tried it on a Titan-X GPU. We did not try any lighter network since we rather went for accuracy, and the speed was quite fast compared to the state of the art (at that time).

**Comment by feitiandemiaomi** [comment]
Thank you for your timely reply , I will have a try .
