### ISSUE TITLE
Boundary snapping

### ISSUE THREAD

**Issue by bhack** [scaelles/OSVOS-TensorFlow#2]
Taking a look to the paper tables seems that boundary snapping branch is still relevant.
What we can try to use in this flavour?

**Comment by scaelles** [comment]
The boundary snapping gives a boost of around 2.5% on the IoU metric as shown in the paper. Therefore, it is a refinement of the appearance model (the one that this code reproduces) and not the core of the algorithm. The boundary snapping is implemented in Matlab and implementing it in python would require quite a lot of time so we are not planning to do it. 

In the paper we also tried another refinement using the Fast Bilateral Solver which also gives a nice (but smaller than boundary snapping) improvement and there is code available in python. Thus, I would recommend you to give it a try.

**Comment by bhack** [comment]
There is a [c++ implementation](https://github.com/opencv/opencv/issues/4494)
 if you are interested

**Comment by scaelles** [comment]
Thanks for your suggestion. Also, if you would like to use the boundary snapping, I recommend you to use the [caffe version](https://github.com/kmaninis/OSVOS-caffe).
