### ISSUE TITLE
Time comparison between PyTorch and TensorFlow

### ISSUE THREAD

**Issue by irwinherrmann** [scaelles/OSVOS-TensorFlow#21]
So I did some time benchmarks and found that about 10 epochs takes the following amount of time:

Env:
OS: Ubuntu 16.04
GPU: Dual 1080 TIs with HB SLI bridge

TensorFlow 1.9: 0.85 seconds
PyTorch 0.5: 2.32 seconds

Is this consistent with what you've observed? I'm trying to figure out which of the following is true: 1) this is a side effect of my installation; 2) the TensorFlow version is much more optimized; 3) there is an underlying side effect that makes TensorFlow faster than PyTorch for this network.

**Comment by scaelles** [comment]
We can continue the discussion in the [Pytorch repository.](https://github.com/kmaninis/OSVOS-PyTorch/issues/16)
