### ISSUE TITLE
Contour Branch

### ISSUE THREAD

**Issue by msanzn** [scaelles/OSVOS-TensorFlow#28]
I have the doubt if this implementation includes the contour branch as running the implementation shows the object detected with very strange borders. From the published paper I understand that the contour branch is only used for the parent training and not for the training done with one mask.

in the image !{00024][logo] it can be seen that the border does not match with the back of the vehicle, so by supposing that in imagenet the vehicles data are not in that position.

I would like to know if there is a way a way to improve the contour matching and the detection on object outside imagenet as posters, paintings or road signs.

![00024](https://user-images.githubusercontent.com/49031278/65952960-44d0ff00-e443-11e9-9032-c759a4bc8c99.png)

**Comment by scaelles** [comment]
Hello,
As mentioned in a previous [issue](https://github.com/scaelles/OSVOS-TensorFlow/issues/2), the contour branch is only available in the [Caffe version](https://github.com/kmaninis/OSVOS-caffe). The countour branch is trained separately and only joined with the appearance branch at test time. The network is not trained for any specific category and it should be able to segmentat any object category given the mask for that object in the first frame of a video.

**Comment by msanzn** [comment]
I am triying to use the Fast Bilateral Solver to see the improvement in the my testing frames, in the opencv website I had only found the implementation and example in python. Also it would be great if could explain if you introduced the mask image or if it is necessary some prior conversion.
