### ISSUE TITLE
Parent model

### ISSUE THREAD

**Issue by j50888** [scaelles/OSVOS-TensorFlow#6]
Hi,
I wanna get the parent model(w/o boundary snapping) which reach 77.4 mioU
I used the provided model(which finetuned 2k iterations) only reach 76.3 mioU
Is there any training policy to reproduce the 77.4 mioU performance?
Or could you provide the model?
Thank you!

**Comment by scaelles** [comment]
Hello,
The model that reaches 77.4 mIoU is the Caffe model provided [here](https://github.com/kmaninis/OSVOS-caffe). The performance of the Tensorflow model is slightly lower. I have replicated the forward pass of the Caffe and Tensorflow models so I guess the difference in the final mIoU may be in the training phase.

**Comment by j50888** [comment]
Thanks
