### ISSUE TITLE
Why should make the deconvolutional part untrainable

### ISSUE THREAD

**Issue by Beanocean** [scaelles/OSVOS-TensorFlow#9]
https://github.com/scaelles/OSVOS-TensorFlow/blob/f1eef4991547547c2a1a9fa720b3c832252b2617/osvos.py#L97

The code above shows the deconvolution layers are set to be untrainable, would you please help to explain this?

**Comment by scaelles** [comment]
We tried training the deconvolutional layers using the bilinear interpolation weights as initialization or directly training from scratch. The best result was obtained using the biliniear interpolation weights, but the performance was almost the same if we trained those layers or not, so we decided not train them.
